# Generated by Django 6.0.6 on 2026-07-29 14:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('hoja_de_vida', models.FileField(blank=True, null=True, upload_to='hojas_de_vida/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Hoja de Vida (PDF)')),
                ('etapa_actual', models.CharField(choices=[('postulado', 'Postulado'), ('preseleccion', 'Preselección'), ('entrevista', 'Entrevista'), ('evaluacion', 'Evaluación'), ('oferta', 'Oferta'), ('contratado', 'Contratado'), ('rechazado', 'Rechazado')], default='postulado', max_length=15, verbose_name='Etapa Actual')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Reclutador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Reclutador',
                'verbose_name_plural': 'Reclutadores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('telefonica', 'Telefónica')], max_length=15, verbose_name='Modalidad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas', to='reclutamiento.candidato', verbose_name='Candidato')),
                ('reclutador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrevistas', to='reclutamiento.reclutador', verbose_name='Reclutador')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Puntuación (1-5)')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('recomendacion', models.CharField(choices=[('contratar', 'Contratar'), ('considerar', 'Considerar'), ('rechazar', 'Rechazar')], max_length=15, verbose_name='Recomendación')),
                ('entrevista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='reclutamiento.entrevista', verbose_name='Entrevista')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Salario Ofrecido')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('fecha', models.DateField(verbose_name='Fecha de Oferta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='reclutamiento.candidato', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Puesto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('departamento', models.CharField(choices=[('tecnologia', 'Tecnología'), ('marketing', 'Marketing'), ('ventas', 'Ventas'), ('rrhh', 'Recursos Humanos'), ('finanzas', 'Finanzas'), ('operaciones', 'Operaciones'), ('legal', 'Legal'), ('administracion', 'Administración'), ('otro', 'Otro')], max_length=50, verbose_name='Departamento')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=15, verbose_name='Modalidad')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Salario')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de Publicación')),
                ('fecha_cierre', models.DateField(verbose_name='Fecha de Cierre')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('pausada', 'Pausada')], default='abierta', max_length=10, verbose_name='Estado')),
                ('fuente', models.CharField(choices=[('linkedin', 'LinkedIn'), ('portal_web', 'Portal Web'), ('referido', 'Referido'), ('otro', 'Otro')], default='portal_web', max_length=30, verbose_name='Fuente de Reclutamiento')),
                ('reclutador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacantes', to='reclutamiento.reclutador', verbose_name='Reclutador Responsable')),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatos', to='reclutamiento.vacante', verbose_name='Vacante Postulada'),
        ),
    ]
