# Generated by Django 6.0.6 on 2026-08-05 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0002_add_perfil_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidato_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de Usuario'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('reclutador', 'Reclutador'), ('coordinador', 'Coordinador'), ('candidato', 'Candidato')], default='reclutador', max_length=15, verbose_name='Rol'),
        ),
    ]
